### ISSUE TITLE
Issue with Deployment of amazon-cloudwatch-monitor-for-sap-hana server less application

### ISSUE THREAD

**Issue by Rajdeepkoch** [aws-samples/amazon-cloudwatch-monitor-for-sap-hana#1]
We are getting authorization error while trying to deploy amazon-cloudwatch-monitor-for-sap-hana server less application. We have assigned all required authorization needed for deploying this. We are getting the error "you are not authorized to perform serverlessrepo:CreateCloudFormationTemplate" while trying to deploy although we have assigned the required authorization. We have seen that while trying to deploy its internally taking us to eu-central-1 region where as we are trying to deploy in us-east-1 region, eu-central-1 region is locked in the account. Also while providing the required authorization we didnot assign it to any ARN but marked as '*' so we are not sure why its failing. Can you please help here.

**Comment by frumania** [comment]
Hi,
AWS support did also contact me on this matter.
While i believe this is related to some IAM issues, that are not in my control, as a workaround, you can download and deploy via CloudFormation directly. Please use the respective templates i created:
[North Virginia (us-east-1)](https://github.com/aws-samples/amazon-cloudwatch-monitor-for-sap-hana/blob/master/packaged_us_east_1.yml)
[Oregon (us-west-2)](https://github.com/aws-samples/amazon-cloudwatch-monitor-for-sap-hana/blob/master/packaged_us_west_2.yml)

**Comment by Rajdeepkoch** [comment]
> Hi,
> AWS support did also contact me on this matter.
> While i believe this is related to some IAM issues, that are not in my control, as a workaround, you can download and deploy via CloudFormation directly. Please use the respective templates i created:
> [North Virginia (us-east-1)](https://github.com/aws-samples/amazon-cloudwatch-monitor-for-sap-hana/blob/master/packaged_us_east_1.yml)
> [Oregon (us-west-2)](https://github.com/aws-samples/amazon-cloudwatch-monitor-for-sap-hana/blob/master/packaged_us_west_2.yml)

**Comment by Rajdeepkoch** [comment]
thanks for the reply. I was finally able to deploy it using the cloud formation template but when i am trying to test the lambda function i am getting the below error. Can you please help here to understand as to what could be the issue here. It says the host name is not known then i deployed again with FQDN still it gives me the same error. I can confirm that the instance is located in the same region where i have deployed this & even i am able to view the instance in ec2. but not sure why the error says so.

Update: When re-tried with IP Address it worked inspite of FQDN
----------------------------------------------------------------------------------------------------------------------

"errorType": "Error",
  "errorMessage": "Connection failed (RTE:[89001] Cannot resolve host name 'xxx.xxx.com' rc=-2: Name or service not known (xxx.xxx.com:32013))",
  "trace": [
    "Error: Connection failed (RTE:[89001] Cannot resolve host name 'xxx.xxx.com' rc=-2: Name or service not known (xxx.xxx.com:32013))",
    "    at Socket.<anonymous> (/var/task/node_modules/@sap/hana-client/lib/index.js:52:13)",
    "    at Socket.emit (events.js:314:20)",
    "    at Socket.EventEmitter.emit (domain.js:483:12)",
    "    at addChunk (_stream_readable.js:298:12)",
    "    at readableAddChunk (_stream_readable.js:273:9)",
    "    at Socket.Readable.push (_stream_readable.js:214:10)",
    "    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)"
  ]
}

**Comment by Rajdeepkoch** [comment]
> Hi,
> AWS support did also contact me on this matter.
> While i believe this is related to some IAM issues, that are not in my control, as a workaround, you can download and deploy via CloudFormation directly. Please use the respective templates i created:
> [North Virginia (us-east-1)](https://github.com/aws-samples/amazon-cloudwatch-monitor-for-sap-hana/blob/master/packaged_us_east_1.yml)
> [Oregon (us-west-2)](https://github.com/aws-samples/amazon-cloudwatch-monitor-for-sap-hana/blob/master/packaged_us_west_2.yml)

hanks for the reply. I was finally able to deploy it using the cloud formation template but when i am trying to test the lambda function i am getting the below error. Can you please help here to understand as to what could be the issue here. It says the host name is not known then i deployed again with FQDN still it gives me the same error. I can confirm that the instance is located in the same region where i have deployed this & even i am able to view the instance in ec2. but not sure why the error says so.

Update: When re-tried with IP Address it worked inspite of FQDN

"errorType": "Error",
"errorMessage": "Connection failed (RTE:[89001] Cannot resolve host name 'xxx.xxx.com' rc=-2: Name or service not known (xxx.xxx.com:32013))",
"trace": [
"Error: Connection failed (RTE:[89001] Cannot resolve host name 'xxx.xxx.com' rc=-2: Name or service not known (xxx.xxx.com:32013))",
" at Socket. (/var/task/node_modules/@sap/hana-client/lib/index.js:52:13)",
" at Socket.emit (events.js:314:20)",
" at Socket.EventEmitter.emit (domain.js:483:12)",
" at addChunk (_stream_readable.js:298:12)",
" at readableAddChunk (_stream_readable.js:273:9)",
" at Socket.Readable.push (_stream_readable.js:214:10)",
" at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)"
]
}
