### ISSUE TITLE
Monitoring of the HANA Scale Out systems

### ISSUE THREAD

**Issue by MykhailoPrykhodko** [aws-samples/amazon-cloudwatch-monitor-for-sap-hana#2]
Hi, do you have an idea regarding the monitoring of the Hana scale-out or multitenant installations?
For example, the script will return only rundom hosts in case of the scale-out and only the first tenant in case of multi-tenant installation.
select TOP 1 
	TO_TIMESTAMP(TO_VARCHAR("TIME", 'YYYY-MM-DD HH24:MI')) "TIME",
	HOST,
	PORT,
	MAX(CPU) "CPU_PCT_INDEXSERVER",
	MAX(SYSTEM_CPU) "SYSTEM_CPU_PCT_INDEXSERVER",
	ROUND(MAX(MEMORY_USED)/1024/1024/1024, 1) "MEMORY_USED_GB",
	ROUND(MAX(MEMORY_ALLOCATION_LIMIT)/1024/1024/1024, 1) "MEMORY_ALLOCATION_LIMIT_GB",
	MAX(CS_UNLOAD_COUNT) "CS_UNLOAD_COUNT",
	MAX(SWAP_IN) "SWAP_IN_BYTE",
	MAX(PING_TIME) "PING_TIME_MS",
	MAX(PENDING_SESSION_COUNT) "PENDING_SESSION_COUNT",
	MAX(MVCC_VERSION_COUNT) "MVCC_VERSION_COUNT",
	MAX(WAITING_THREAD_COUNT) "WAITING_THREAD_COUNT",
	MAX(BLOCKED_TRANSACTION_COUNT) "BLOCKED_TRANSACTION_COUNT"
from 
	"M_LOAD_HISTORY_SERVICE"
WHERE
	PORT LIKE '%03'
group by
	TO_TIMESTAMP(TO_VARCHAR("TIME", 'YYYY-MM-DD HH24:MI')),
	HOST,
	PORT
order by
    TIME desc

**Comment by frumania** [comment]
Hi Mykhailo,

sry for the late feedback!
Thanks for spotting this!
Indeed, the solution for now is considering SCALE UP / SingleNode Environments only.
I will make this clear in the documentation!
