### ISSUE TITLE
Password change needed

### ISSUE THREAD

**Issue by gitjps** [aws-samples/amazon-cloudwatch-monitor-for-sap-hana#3]
For user SAPMONITOR a password change was needed so the initial test failed after establishing the connection and some SQL statements (at least visible in the log).
Solution:
- delete the cloud formation stack
- Login in HANA DB as SAPMONITOR :  hdbsql -n 10.1.1.5 -i 02 -u SAPMONITOR -p ...; enter/confirm new password
- create lambda function again

**Comment by frumania** [comment]
Hi Peter,
actually after password expiration, after HANA update, you can just go and update the password in AWS Secrets Manager.
No need to redeploy the whole stack!
Warm Regards,
Marcel
