### ISSUE TITLE
Encryption error upon connection to hana server

### ISSUE THREAD

**Issue by btorretta** [aws-samples/amazon-cloudwatch-monitor-for-sap-hana#4]
Hello, I am receiving the following error, please note I am not exactly a hana or nodejs expert but I believe that in the hana environment, there is a requirement to connect over the commoncryto.

2021-08-12T21:40:36.471Z	29682b0a-e155-4168-9f71-847fa6dc91f7	INFO	Establishing SAP HANA connection to <redacted> as MONITOR...
2021-08-12T21:40:36.519Z	29682b0a-e155-4168-9f71-847fa6dc91f7	ERROR	Uncaught Exception 	{"code":4321,"message":"only secure connections are allowed","sqlState":"HY000"}

Looking into the node library, looks like I can set a connection option to enable TLS, per line 27 of step 3: https://developers.sap.com/tutorials/hana-clients-node.html

That said, I'd like to update the connect.js code but it's a little unclear to me where I'd insert those TLS connection options. I tried a number of options modifying the file from a zip file but I haven't been able to insert the option. Is there any guidance for this issue?

**Comment by frumania** [comment]
Let me see, I should be able to fix this / offer a solution. Stay tuned!

**Comment by frumania** [comment]
Sry for the late update!

I have added a new property to establish a secure connection within the HANA client - see also
https://github.com/aws-samples/amazon-cloudwatch-monitor-for-sap-hana/blob/master/code/connect.js

If you update/redeploy the CloudFormation Stack and add a new property in AWS Secrets Manager called "secureConnection" = "true", it should do the job:

![secure](https://user-images.githubusercontent.com/12220576/130847230-866a5281-6033-4e94-8dff-3f969daeed48.png)

A successful secure connection should read as

_2021-08-25T18:30:21.611Z	2e529ecf-e6db-4c18-8405-e6a7ae2242fa	INFO	Establishing **!secure!** SAP HANA connection to..._

in CloudWatch Logs.

**Kindly let me know, if it works for you!!**

**Note:** As this point, there is no server-side certificate verification. If you need this feature as well, let me know!
