### ISSUE TITLE
monitor-for-sap-hana | Issue with repl_status.sql

### ISSUE THREAD

**Issue by lcampiol** [aws-samples/amazon-cloudwatch-monitor-for-sap-hana#5]
Hi,
I´d configured the hana monitor with this but the "REPL_STATUS" wasn't retrieving the correct value with the current sql because a case sensitive issue.
It worked after the following adjustment:

FROM:
`select top 1 (case when replication_status = 'active' then 1 when replication_status = 'error' then -1 else 0 end) AS REPLICATION_STATUS from SYS.m_service_replication;`

TO:
`select top 1 (case when lower(replication_status) = 'active' then 1 when lower(replication_status) = 'error' then -1 else 0 end) AS REPLICATION_STATUS from SYS.m_service_replication;`

**Comment by frumania** [comment]
Thx, i will change this!
